[book]
#  This book is called
title = "Rust 中的命令行应用"
# ...but friends call it "Clair"
authors = ["The Rust CLI Working Group"]
multilingual = false
language = "zh"
src = "src"

[output.html]
curly-quotes = true
additional-css = ["src/special-content.css"]
git-repository-url = "https://github.com/suibianxiedianer/rust-cli-book-zh_CN"
site-url = "/book/"

# Linkcheck doesn't find images/SVG so it's not enabled for now
# [output.linkcheck]
