name: ci

on:
  push:
    branches: [ zh_CN ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install MDBook
      run: cargo install mdbook
    - name: Choose summary
      run: cp src/SUMMARY_zh.md src/SUMMARY.md
    - name: Build
      run: mdbook build

